CREATE DATABASE Quan_Li_TV;
GO

USE Quan_Li_TV;
GO







CREATE TABLE HoaDon (
    MaHD VARCHAR(10) PRIMARY KEY,
    NgayLap DATE NOT NULL,
    ThanhTien DECIMAL(18,2) DEFAULT 0
);
GO

CREATE TABLE SanPham (
    MaSP VARCHAR(10) PRIMARY KEY,
    TenSP NVARCHAR(100) NOT NULL,
    SLConLai INT DEFAULT 0,
    SoTien DECIMAL(18,2) DEFAULT 0
    NhaCC NVARCHAR(100) NOT NULL,
    NgayNhap DATE NOT NULL,
);
GO



CREATE TABLE ChiTietHoaDon (
    MaHD VARCHAR(10) NOT NULL,
    MaSP VARCHAR(10) NOT NULL,
    SoLuong INT NOT NULL,
    DonGiaBan DECIMAL(18,2) NOT NULL,
    NgayMua DATE DEFAULT GETDATE(),
    TenKH VARCHAR(10),
    SDT     VARCHAR(10),
    TenNV  VARCHAR(10),
    PRIMARY KEY (MaHD, MaSP),
    FOREIGN KEY (MaHD) REFERENCES HoaDon(MaHD),
    FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP),
);
GO
